#!/bin/sh
file=$1.dvi
for i in `dvitype -output-level 0 $file | sed -n '/^Postamble starts at byte/,${s/^Font [0-9]\+: \([.[:alnum:]/]\+\).*/\1/p}'`; do
  if [ $i = ${i#*/} ]; then
    grep -q "^$i " ~/lhplain/cmfonts.map ~/lhplain/niceframe.map && continue;
    [ -e ~/lhplain/vf/$i.vf ] && continue;
    echo PK fonts not appropriate in PDF
    exit
  else
    echo Fonts with path not allowed in map-file
    exit
  fi
done
eval "$(hexdump -s15 -n `hexdump -s14 -n1 -e '"%u"' $file` -v -e '"%c"' $file | sed 's/.* /p=/;s/x/sp,/;s/[+-][0-9]*/sp x=& y=/')"
export TEXCONFIG=~/lhplain:~/dvips
export DVIPSHEADERS=~/lhplain:~/dvips
export VFFONTS=~/lhplain/vf
export TEXFONTS=~/lhplain/tfm:~/tex/TeXfonts
t=a4
[ $p = 55380990sp,39158276sp ] && t='a4 -t landscape'
~/dvips/dvips -t $t -O $((x-4736287))sp,$((y-4736287))sp -P t1 -q $file
if [ $? = 0 ]; then
  ps2pdf $1.ps $1.pdf || echo PS2PDF ERROR
else
  echo DVIPS ERROR
fi
