#!/bin/sh
export TEXCONFIG=~/lhplain:~/dvips
export DVIPSHEADERS=~/lhplain:~/dvips
export VFFONTS=~/lhplain/vf
export TEXFONTS=~/lhplain/tfm:~/tex/TeXfonts
export PKFONTS=/none
file=$1.dvi
eval "$(hexdump -s 15 -n `hexdump -s 14 -n 1 -e '/1 "%d"' $file` -v -e '/1 "%c"' $file | sed 's/.* /p=/;s/x/sp,/;s/[+-][0-9]*/sp x=& y=/')"
~/dvips/dvips -T $p -O $((x-4736287))sp,$((y-4736287))sp -q -P t1 -M $file
ret=$?
if [ -e missfont.log ]; then
  rm missfont.log
  echo Bitmap fonts are not allowed in PDF.
  exit
fi
if [ $ret = 0 ]; then
  sed '0,/^%%Title/{//d}' $1.ps | ps2pdf - $1.pdf # 'okular' tries to show Title by default, and fails to do it correctly if Title contains UTF-8
  [ $? = 0 ] || echo PS2PDF ERROR
else
  echo DVIPS ERROR
fi
