#!/bin/sh
rm omfonts.map vf/* tfm/*

# split each om-font into two fonts: lower half (xx) and upper half (yy),
# in order to be able to use appropriate Type1 font for each half (see omfonts.map)

for i in `sed -n '/% \w\+[0-9]\+$/s/\(\w\+[0-9]\+\).*% /\1_/p' cmfonts.map`; do
  cm=${i%_*}
  sf=${i#*_}
  om=om${cm#cm}
  xx=xx${om#om}
  yy=yy${om#om}
  printf '%s %s <%s.pfb\n' $xx $(echo $cm|tr a-z A-Z) $cm >>omfonts.map
  printf '%s %s "OMEncoding ReEncodeFont" <cm-super-om.enc <%s.pfb\n' \
                           $yy $(echo $sf|tr a-z A-Z) $sf >>omfonts.map
  tftopl ~/tex/TeXfonts/$om.tfm >$om.vpl
  dsize=$(sed -n 's/^(DESIGNSIZE/(FONTDSIZE/p' $om.vpl)
  sed -i "1i (MAPFONT D 0 (FONTNAME $xx) $dsize)" $om.vpl
  sed -i "1a (MAPFONT D 1 (FONTNAME $yy) $dsize)" $om.vpl
  sed -i 's/^(CHARACTER O \([23][0-9][0-9]\)/&\n   (MAP (SELECTFONT D 1) (SETCHAR O \1))/' $om.vpl
  ln -s ../../tex/TeXfonts/$om.tfm tfm/$xx.tfm
  ln -s ../../tex/TeXfonts/$om.tfm tfm/$yy.tfm
  TEXFONTS=tfm vptovf $om.vpl vf/$om.vf /tmp/discard.tfm
  rm $om.vpl
done
